-- AlterTable
ALTER TABLE `transactions` ADD COLUMN `category` ENUM('FOOD', 'RENT', 'FASHION', 'SHOPPING', 'GROCERIES', 'TRANSPORT', 'HEALTH', 'ENTERTAINMENT', 'UTILITIES', 'EDUCATION', 'TRAVEL', 'INSURANCE', 'SAVINGS', 'OTHER') NULL;
